### ISSUE TITLE
父子元素 滚动条

### ISSUE THREAD

**Issue by eyea** [eyea/dailyIssues#31]
假设元素为 <code>el</code>，子元素为 <code>son</code>，孙子元素为 <code>gson</code>
孙子元素的大小(以高度举例)，当孙子元素高度大于子元素高度，同时子元素的高度是小于元素的，需要添加<code>border</code>

```html
  <div class="el">
    <div class="son">
      <div class="gson"></div>      
    </div>
  </div>
```
其对应的 `css` 为
```css
.el {
  width: 600px;
  height: 300px;
  border: 2px solid red;
  border-radius: 50px;
  background-color: #eee;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%); 
}
.son {
  overflow: auto;
  width: 600px;
  height: 300px;
}
.gson {
  width: 600px;
  height: 600px;
  border: 2px solid green;
}
```
我们会发现这样的奇葩现象
![1516890504986](https://user-images.githubusercontent.com/17020223/35393231-5ca4ddf2-021f-11e8-9757-43050c568af5.jpg)
红色部分才是爸爸啊，儿子上天了。。。
<hr/>

原因放在下面，先给老板看方案
![1516890907669](https://user-images.githubusercontent.com/17020223/35393480-0bc2bc14-0220-11e8-90d1-bbd8d50ce046.jpg)
```css
.el {
  // other styles
  overflow: hidden;
}
```
<hr/>
but, 细心的老板发现了，绿色那条线是什么鬼？
于是，粗心的我们补上这么一刀：

![1516891163286](https://user-images.githubusercontent.com/17020223/35393676-9e7195da-0220-11e8-8dc4-75708d0b5a5b.jpg)
```css
.el {
  // other styles
   box-sizing: border-box;
}
```
![1516891625238](https://user-images.githubusercontent.com/17020223/35394365-911b3254-0222-11e8-8d59-a2ff0ad79eaf.jpg)

呵呵，`css` ...
给 `class` 为 `gson` 添加内容 `gson`， 给其样式添加 `padding: 10px;`，同时别忘了给添加边框的 `gson` 添加样式

```css
.gson {
  // other style
  padding: 10px;
  box-sizing: border-box;
}
```
现在你的模样
![1516891970260](https://user-images.githubusercontent.com/17020223/35394343-868d595c-0222-11e8-880f-8f6f5ed6c4b1.jpg)

现在任务就是把绿色的边框去掉
说实话，绕了很多弯，发现，为什么要加这个边框呢？
直接干掉了。
![1516892160785](https://user-images.githubusercontent.com/17020223/35394527-f113016e-0222-11e8-9f25-9c6042e3c5a0.jpg)

全剧终。
